# Generated by Django 3.2.8 on 2021-12-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=32)),
                ('placeId', models.CharField(max_length=32)),
                ('parent', models.CharField(max_length=32)),
            ],
        ),
    ]
